env:
  secure: <secret>
language: ruby
dist: focal
rvm:
- 2.6.5
cache:
  directories:
  - node_modules
  - vendor/bundle
before_install:
- gem install bundler:1.17.3
- nvm install 12.13.1
- npm install -g yarn@1.22.4
before_script:
- bundle install
- yarn install
script:
- RAILS_ENV=test bundle exec rake db:create --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
  #- bundle exec rspec
  #- bundle exec cucumber
